### PR TITLE
Added a file parameter for file inclusion

### PR DESCRIPTION
**Pull request by tkhduracell**
Background: Incremental build fails in larger projects, due to the command line reaching max allowed characters. 

Will create a corresponding update in the Gradle plugin. 
```
  retrolambda.includedFile
      A file listing the files to process (one file per line), instead of processing all files.
      This is useful for a build tool to support incremental compilation.
```

### CODE REVIEW

**Comment by tkhduracell** [comment]
@orfjackal

**Comment by orfjackal** [comment]
Thanks. I'll work on this in near future, when I find the time. A similar thing is needed also at least for the classpath.

**Comment by tkhduracell** [comment]
Okey, let's merge it then?

**Comment by orfjackal** [comment]
This is included in Retrolambda 2.1.0. The gradle plugin will still need to be updated.

**Comment by tkhduracell** [comment]
Great, just wanted to make it easy for me in that update ;)

**Pull request merged**
