### PR TITLE
Rewrite calls to Objects.requireNonNull

### LINKED ISSUE #75: Rewrite generated calls to Objects.requireNonNull()
In JDK 8 and below, javac generates synthetic null-checks by calling `Object.getClass`. Starting in JDK 9, `Objects.requireNonNull()` is used if it is available (see [JDK-8074306](https://bugs.openjdk.java.net/browse/JDK-8074306)).

This prevents retrolambda users from compiling code with JDK9 and running it on JDK6 or below, since `java.util.Objects` was introduced in JDK7.

When targeting JDK < 7, retrolambda should rewrite the generated calls to `requireNonNull`.

### PR DESCRIPTION
**Pull request by cushon**
requireNonNull is only available in JDK 7 and above.

Starting in JDK 9, javac uses requireNonNull for synthetic null-checks,
see: http://bugs.openjdk.java.net/browse/JDK-8074306

Fixes #75

### CODE REVIEW

**Comment by ben-manes** [comment]
@orfjackal I'd really love to see this go through. It feels dirty not having error prone running :-)

**Comment by orfjackal** [comment]
Thanks. Sorry for taking so long to merge it. Been busy lately.

**Comment by JakeWharton** [comment]
I would love to get my PRs looked at as well 😀 . I ended up releasing a fork that we've been using for 3+ months: https://github.com/JakeWharton/retrolambda which drastically reduces the generated methods.

**Comment by orfjackal** [comment]
@JakeWharton OK. :) No promises, but I'll try to do it soon.

**Pull request merged**
